Lint/HandleExceptions:
  Exclude:
    - spec/support/*.rb

Style/CommandLiteral:
  Enabled: false

Style/MultilineIfThen:
  Enabled: false

Style/GuardClause:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Layout/FirstParameterIndentation:
  Enabled: false
