require: 
  - rubocop-rspec

Lint/HandleExceptions:
  Exclude:
    - spec/support/*.rb

Style/CommandLiteral:
  Enabled: false

Style/MultilineIfThen:
  Enabled: false

Style/GuardClause:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Layout/IndentFirstArgument:
  Enabled: false

Layout/AlignArguments:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Metrics/MethodLength:
  Max: 25

Style/Documentation:
  Exclude:
    - spec/**/*
    - test/**/*
    - features/**/*
    - app/controllers/**/*
    - app/models/**/*
    - app/helpers/**/*
    - app/controllers/**/*
    - app/jobs/**/*
