version: '2'

services:
  mysql:
    image: docker.io/library/mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "Sh0wT!meR00t"
      MYSQL_DATABASE: showtime_development
      MYSQL_USER: showtime
      MYSQL_PASSWORD: "Sh0wT!me"
    volumes:
      - .docker/data/mysql:/var/lib/mysql
      - .docker/initdb.d:/docker-entrypoint-initdb.d

  app:
    # tty: true
    #image: docker.io/bitnami/rails:5
    build:
      context: .
      dockerfile: .docker/Dockerfile
    environment:
      DATABASE_HOST: mysql
      SHOWTIME_DATABASE_URL: mysql2://mysql/showtime_development
      SHOWTIME_FUSIONDB_URL: mysql2://mysql/dragonhall_utf8
      SHOWTIME_DATABASE_USER: showtime
      SHOWTIME_DATABASE_PASSWORD: "Sh0wT!me"
    depends_on: 
      - mysql
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - .docker/config/database.yml:/app/config/database.yml
      # - .docker/data/gems:/opt/bitnami/ruby/lib/ruby/gems
    command:
      - bundle
      - exec
      - guard
      - start
      - -i

