services:
  nginx:
    image: nginx:latest
    volumes:
      - ../:/app
      - ./config/nginx/ssl:/etc/nginx/ssl
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443
    depends_on:
      - rails

