user  www-data;
worker_processes  1;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

# pid        /run/nginx-rtmp.pid;

#load_module /opt/nginx-with-rtmp/modules/ngx_rtmp_module.so;

events {
    worker_connections  1024;
}


rtmp {
    max_streams 64;
    max_connections 1024;

    buflen 1s;
    max_message 300k;

    server {
        listen 1935;
        chunk_size 4000;

        application live {
            live on;
            hls on;
            hls_path /var/cache/nginx-rtmp/hls/;
            hls_fragment 3;
            hls_playlist_length 20;
            deny play all;

            allow publish ::1;
            allow publish 127.0.0.1;
            allow publish 89.133.128.232;
            allow publish 92.119.122.184;
            allow publish 37.191.37.99;
            allow publish 87.229.7.176;

            deny publish all;

        }


    }
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    #gzip  on;

    proxy_headers_hash_max_size 1024;
    proxy_headers_hash_bucket_size 128;

    server {
        listen 80 default_server;

        root /opt/nginx-with-rtmp/html;

        location /live/ {
            alias /var/cache/nginx-rtmp/hls;
            add_header Access-Control-Allow-Origin "*";
        }
    }

}

# vim: ts=4 sw=4 et
