#!/bin/sh


ME="$(readlink -f "$0")"
MYDIR=$(dirname "${ME}")


hostname="$(hostname -s)"
RAILS_ENV="${RAILS_ENV:-development}"
RAILS_ROOT=$(dirname "${MYDIR}")
RAILS_CMD=$(basename "${ME}")

if [ "$1" = "-e" ]; then
  RAILS_ENV=$2
  shift
  shift
fi

export RAILS_ENV

if [ "${RAILS_ENV}" = "development" ]; then
  exec spring rails "${RAILS_CMD}" -e "${RAILS_ENV}" "$@"
else
  exec bundle exec rails "${RAILS_CMD}" -e "${RAILS_ENV}" "$@"
  :;
fi
